manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: v3.7.1
      clone-depth: 1
      import:
        path-prefix: external
    - name: secp256k1-frost
      path: external/modules/crypto/secp256k1-frost
      url: https://github.com/bancaditalia/secp256k1-frost
      revision: frost
